# This is an example secrets file.
# To run this app, create a copy of this file named 'secrets.toml'
# and replace the placeholder with your actual Google AI API key.

GOOGLE_API_KEY = "YOUR_API_KEY_HERE"
